<!DOCTYPE html>
<html lang="es">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <title>Ejercicio MVC</title>
        <meta charset="UTF-8" />
        <title>Personas</title>
      <script>
      .padre {
        background: yellow;
        height: 150px;
        /*IMPORTANTE*/
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .hijo {
        background: red;
        width: 120px;
      }
      </script>
    </head>
    <body>
      <div>
        <h4 class="text-center">Ejercicio MVC</h4>
      </div>
      <div class="col-3 padre">
					<table class="table hijo">
							<h3 style="text-align:center;color: #92a8d1;">Registros de usuario</h3>
							<tr>
								<br/>
								<td style="text-align:center"><strong>Nombre</strong></td>
								<td style="text-align:center"><strong>Apellido</strong></td>
                <td style="text-align:center"><strong>Ciudad</strong></td>
							</tr>
              <?php
                  foreach ($datos as $dato) {
                    ?>
                    <tr>
    									<td style="text-align:center"><?php echo $dato["_nombre"];?></td>
    									<td style="text-align:center"><?php echo $dato["_apellido"];?></td>
                      <td style="text-align:center"><?php echo $dato["_ciudad"];?></td>
    								</tr>
    								<?php
                  }
              ?>
            </table>
          </div>
        </div>
    <footer>
    <div>
        <p class="text-center">Designed by <a href="https://www.linkedin.com/in/andres-felipe-miranda-diaz-26910366/   originalSubdomain=es" target=”_blank”>&copy; Andres Miranda 2020</a></p>
    </div>
    </footer>
    </body>
</html>
